In [1]:
import pickle
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [2]:
with open('merge_df.pickle', 'rb') as f:
    merge_df = pickle.load(f)

In [3]:
def lsttostrlst(lst_lst):
    merge_str=[]
    for lst in lst_lst:
        merge_str.append(' '.join(lst))
    return merge_str

In [4]:
count_vectorizer_stem = CountVectorizer(ngram_range=(1, 1), analyzer='word', max_df=0.9, max_features = 1000,
                                        stop_words='english', binary=False, tokenizer=str.split)

In [5]:
str_stemmed = lsttostrlst(merge_df['tweet_stemmed'])
bag_of_words_stem = count_vectorizer_stem.fit_transform(str_stemmed)

feature_names = count_vectorizer_stem.get_feature_names()
pd.DataFrame(bag_of_words_stem.toarray(), columns = feature_names)

abl  absolut  accept  account  act  action  actor  actual  ad  adapt  \
0        0        0       0        0    0       0      0       0   0      0   
1        0        0       0        0    0       0      0       0   0      0   
2        0        0       0        0    0       0      0       0   0      0   
3        0        0       0        0    0       0      0       0   0      0   
4        0        0       0        0    0       0      0       0   0      0   
...    ...      ...     ...      ...  ...     ...    ...     ...  ..    ...   
49154    0        0       0        0    0       0      0       0   0      0   
49155    0        0       0        0    0       0      0       0   0      0   
49156    0        0       0        0    0       0      0       0   0      0   
49157    0        0       0        0    0       0      0       0   0      0   
49158    0        0       0        0    0       0      0       0   0      0   

       ...  yo  yoga  york  young  youtub  yoyou  yoyour  yoyoy  yr  yummi  
0      ...   0     0     0      0       0      0       0      0   0      0  
1      ...   0     0     0      0       0      0       0      0   0      0  
2      ...   0     0     0      0       0      0       0      0   0      0  
3      ...   0     0     0      0       0      2       1      0   0      0  
4      ...   0     0     0      0       0      0       0      0   0      0  
...    ...  ..   ...   ...    ...     ...    ...     ...    ...  ..    ...  
49154  ...   0     0     0      0       0      0       0      0   0      0  
49155  ...   0     0     0      0       0      0       0      0   0      0  
49156  ...   0     0     0      0       0      0       0      0   0      0  
49157  ...   0     0     0      0       0      0       0      0   0      0  
49158  ...   0     0     0      0       0      0       0      0   0      0  

[49159 rows x 1000 columns]

In [6]:
count_vectorizer_lem = CountVectorizer(ngram_range=(1, 1), analyzer='word', max_df=0.9, max_features = 1000, 
                                       stop_words='english', binary=False, tokenizer=str.split)

In [7]:
str_lematized = lsttostrlst(merge_df['tweet_lemmatized'])
bag_of_words_lem = count_vectorizer_lem.fit_transform(str_lematized)

feature_names = count_vectorizer_lem.get_feature_names()
pd.DataFrame(bag_of_words_lem.toarray(), columns = feature_names)

able  absolutely  account  act  action  actor  actually  adapt  add  \
0         0           0        0    0       0      0         0      0    0   
1         0           0        0    0       0      0         0      0    0   
2         0           0        0    0       0      0         0      0    0   
3         0           0        0    0       0      0         0      0    0   
4         0           0        0    0       0      0         0      0    0   
...     ...         ...      ...  ...     ...    ...       ...    ...  ...   
49154     0           0        0    0       0      0         0      0    0   
49155     0           0        0    0       0      0         0      0    0   
49156     0           0        0    0       0      0         0      0    0   
49157     0           0        0    0       0      0         0      0    0   
49158     0           0        0    0       0      0         0      0    0   

       adventure  ...  yo  yoga  york  young  youtube  yoyou  yoyour  yoyoyou  \
0              0  ...   0     0     0      0        0      0       0        0   
1              0  ...   0     0     0      0        0      0       0        0   
2              0  ...   0     0     0      0        0      0       0        0   
3              0  ...   0     0     0      0        0      2       1        0   
4              0  ...   0     0     0      0        0      0       0        0   
...          ...  ...  ..   ...   ...    ...      ...    ...     ...      ...   
49154          0  ...   0     0     0      0        0      0       0        0   
49155          0  ...   0     0     0      0        0      0       0        0   
49156          0  ...   0     0     0      0        0      0       0        0   
49157          0  ...   0     0     0      0        0      0       0        0   
49158          0  ...   0     0     0      0        0      0       0        0   

       yr  yummy  
0       0      0  
1       0      0  
2       0      0  
3       0      0  
4       0      0  
...    ..    ...  
49154   0      0  
49155   0      0  
49156   0      0  
49157   0      0  
49158   0      0  

[49159 rows x 1000 columns]

In [8]:
count_tfdfvectorizer_stem = TfidfVectorizer(ngram_range=(1, 1), analyzer='word', max_df=0.9, max_features = 1000, 
                                            stop_words='english', binary=False, tokenizer=str.split)

In [9]:
str_stemmed = lsttostrlst(merge_df['tweet_stemmed'])
bag_of_words_stem = count_tfdfvectorizer_stem.fit_transform(str_stemmed)

feature_names = count_tfdfvectorizer_stem.get_feature_names()
pd.DataFrame(bag_of_words_stem.toarray(), columns = feature_names)

abl  absolut  accept  account  act  action  actor  actual   ad  adapt  \
0      0.0      0.0     0.0      0.0  0.0     0.0    0.0     0.0  0.0    0.0   
1      0.0      0.0     0.0      0.0  0.0     0.0    0.0     0.0  0.0    0.0   
2      0.0      0.0     0.0      0.0  0.0     0.0    0.0     0.0  0.0    0.0   
3      0.0      0.0     0.0      0.0  0.0     0.0    0.0     0.0  0.0    0.0   
4      0.0      0.0     0.0      0.0  0.0     0.0    0.0     0.0  0.0    0.0   
...    ...      ...     ...      ...  ...     ...    ...     ...  ...    ...   
49154  0.0      0.0     0.0      0.0  0.0     0.0    0.0     0.0  0.0    0.0   
49155  0.0      0.0     0.0      0.0  0.0     0.0    0.0     0.0  0.0    0.0   
49156  0.0      0.0     0.0      0.0  0.0     0.0    0.0     0.0  0.0    0.0   
49157  0.0      0.0     0.0      0.0  0.0     0.0    0.0     0.0  0.0    0.0   
49158  0.0      0.0     0.0      0.0  0.0     0.0    0.0     0.0  0.0    0.0   

       ...   yo  yoga  york  young  youtub     yoyou    yoyour  yoyoy   yr  \
0      ...  0.0   0.0   0.0    0.0     0.0  0.000000  0.000000    0.0  0.0   
1      ...  0.0   0.0   0.0    0.0     0.0  0.000000  0.000000    0.0  0.0   
2      ...  0.0   0.0   0.0    0.0     0.0  0.000000  0.000000    0.0  0.0   
3      ...  0.0   0.0   0.0    0.0     0.0  0.744148  0.392399    0.0  0.0   
4      ...  0.0   0.0   0.0    0.0     0.0  0.000000  0.000000    0.0  0.0   
...    ...  ...   ...   ...    ...     ...       ...       ...    ...  ...   
49154  ...  0.0   0.0   0.0    0.0     0.0  0.000000  0.000000    0.0  0.0   
49155  ...  0.0   0.0   0.0    0.0     0.0  0.000000  0.000000    0.0  0.0   
49156  ...  0.0   0.0   0.0    0.0     0.0  0.000000  0.000000    0.0  0.0   
49157  ...  0.0   0.0   0.0    0.0     0.0  0.000000  0.000000    0.0  0.0   
49158  ...  0.0   0.0   0.0    0.0     0.0  0.000000  0.000000    0.0  0.0   

       yummi  
0        0.0  
1        0.0  
2        0.0  
3        0.0  
4        0.0  
...      ...  
49154    0.0  
49155    0.0  
49156    0.0  
49157    0.0  
49158    0.0  

[49159 rows x 1000 columns]

In [10]:
count_tfdfvectorizer_lem = TfidfVectorizer(ngram_range=(1, 1), analyzer='word', max_df=0.9, max_features = 1000, 
                                            stop_words='english', binary=False, tokenizer=str.split)

In [11]:
str_lematized = lsttostrlst(merge_df['tweet_lemmatized'])
bag_of_words_lem = count_tfdfvectorizer_lem.fit_transform(str_lematized)

feature_names = count_tfdfvectorizer_lem.get_feature_names()
pd.DataFrame(bag_of_words_lem.toarray(), columns = feature_names)

able  absolutely  account  act  action  actor  actually  adapt  add  \
0       0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0   
1       0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0   
2       0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0   
3       0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0   
4       0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0   
...     ...         ...      ...  ...     ...    ...       ...    ...  ...   
49154   0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0   
49155   0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0   
49156   0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0   
49157   0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0   
49158   0.0         0.0      0.0  0.0     0.0    0.0       0.0    0.0  0.0   

       adventure  ...   yo  yoga  york  young  youtube     yoyou   yoyour  \
0            0.0  ...  0.0   0.0   0.0    0.0      0.0  0.000000  0.00000   
1            0.0  ...  0.0   0.0   0.0    0.0      0.0  0.000000  0.00000   
2            0.0  ...  0.0   0.0   0.0    0.0      0.0  0.000000  0.00000   
3            0.0  ...  0.0   0.0   0.0    0.0      0.0  0.742113  0.39173   
4            0.0  ...  0.0   0.0   0.0    0.0      0.0  0.000000  0.00000   
...          ...  ...  ...   ...   ...    ...      ...       ...      ...   
49154        0.0  ...  0.0   0.0   0.0    0.0      0.0  0.000000  0.00000   
49155        0.0  ...  0.0   0.0   0.0    0.0      0.0  0.000000  0.00000   
49156        0.0  ...  0.0   0.0   0.0    0.0      0.0  0.000000  0.00000   
49157        0.0  ...  0.0   0.0   0.0    0.0      0.0  0.000000  0.00000   
49158        0.0  ...  0.0   0.0   0.0    0.0      0.0  0.000000  0.00000   

       yoyoyou   yr  yummy  
0          0.0  0.0    0.0  
1          0.0  0.0    0.0  
2          0.0  0.0    0.0  
3          0.0  0.0    0.0  
4          0.0  0.0    0.0  
...        ...  ...    ...  
49154      0.0  0.0    0.0  
49155      0.0  0.0    0.0  
49156      0.0  0.0    0.0  
49157      0.0  0.0    0.0  
49158      0.0  0.0    0.0  

[49159 rows x 1000 columns]

In [12]:
with open('corpus', 'r') as f:
    corpus = f.read()

In [13]:
labels, texts = [], []
for i, line in enumerate(corpus.split("\n")):
    content = line.split()
    labels.append(content[0])
    texts.append(" ".join(content[1:]))

In [14]:
trainDF = pd.DataFrame()
trainDF['text'] = texts
trainDF['label'] = labels
trainDF.head(5)

text       label
0  Stuning even for the non-gamer: This sound tra...  __label__2
1  The best soundtrack ever to anything.: I'm rea...  __label__2
2  Amazing!: This soundtrack is my favorite music...  __label__2
3  Excellent Soundtrack: I truly like this soundt...  __label__2
4  Remember, Pull Your Jaw Off The Floor After He...  __label__2

In [15]:
from sklearn import model_selection, preprocessing, linear_model
from sklearn.metrics import accuracy_score

train_x, valid_x, train_y, valid_y = model_selection.train_test_split(trainDF['text'], trainDF['label'], test_size=0.30)

# labelEncode целевую переменную
encoder = preprocessing.LabelEncoder()
train_y = encoder.fit_transform(train_y)
valid_y = encoder.fit_transform(valid_y)

count_vect = CountVectorizer(ngram_range=(1, 1), analyzer='word', max_df=0.9, max_features = 1000, 
                             stop_words='english', binary=False)

count_vect.fit(trainDF['text'])

xtrain_count =  count_vect.transform(train_x)
xvalid_count =  count_vect.transform(valid_x)

classifier = linear_model.LogisticRegression()
classifier.fit(xtrain_count, train_y)
predictions = classifier.predict(xvalid_count)
predictions

array([1, 1, 0, ..., 0, 0, 0])

In [16]:
accuracy_score(valid_y, predictions)

0.8276666666666667

In [17]:
count_vect = TfidfVectorizer(ngram_range=(1, 2), analyzer='word', max_df=0.9, max_features = 6000,
                             stop_words='english', binary=False)

count_vect.fit(trainDF['text'])

xtrain_count =  count_vect.transform(train_x)
xvalid_count =  count_vect.transform(valid_x)

classifier = linear_model.LogisticRegression()
classifier.fit(xtrain_count, train_y)
predictions = classifier.predict(xvalid_count)
predictions

array([1, 1, 0, ..., 0, 0, 0])

In [18]:
accuracy_score(valid_y, predictions)

0.849

In [19]:
from sklearn.decomposition import PCA, TruncatedSVD
from sklearn.preprocessing import StandardScaler
import numpy as np

In [20]:
pca = TruncatedSVD(n_components=5000)

In [142]:
# scaler = StandardScaler(with_mean=False)
# xtrain_count = scaler.fit_transform(xtrain_count)

In [21]:
pca_stem = pca.fit_transform(xtrain_count)

In [36]:
np.sum(pca.explained_variance_ratio_[:4000])

0.9766371105267684

In [37]:
pca = TruncatedSVD(n_components=4000)
pca_stem_train = pca.fit_transform(xtrain_count)
pca_stem_valid = pca.transform(xvalid_count)

In [38]:
classifier = linear_model.LogisticRegression()
classifier.fit(pca_stem_train, train_y)
predictions = classifier.predict(pca_stem_valid)
predictions

array([1, 1, 0, ..., 0, 0, 0])

In [39]:
accuracy_score(valid_y, predictions)

0.8503333333333334